//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valuify {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IgnoreAttributeAnalyzer_Resources {
        
        private static global::System.Resources.ResourceManager _resourceMan;

        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IgnoreAttributeAnalyzer_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Valuify.IgnoreAttributeAnalyzer.Resources", typeof(IgnoreAttributeAnalyzer_Resources).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is not considered by Valuify because the Valuify attribute has not been applied to the type, so the usage of the Ignore attribute is redundant..
        /// </summary>
        internal static string MissingValuifyRuleDescription {
            get {
                return ResourceManager.GetString("MissingValuifyRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property `{0}` is not considered by Valuify, making the usage of the Ignore attribute redundant..
        /// </summary>
        internal static string MissingValuifyRuleMessageFormat {
            get {
                return ResourceManager.GetString("MissingValuifyRuleMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not utilize Valuify.
        /// </summary>
        internal static string MissingValuifyRuleTitle {
            get {
                return ResourceManager.GetString("MissingValuifyRuleTitle", _resourceCulture);
            }
        }
    }
}
