//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valuify {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValuifyAttributeAnalyzer_Resources {
        
        private static global::System.Resources.ResourceManager _resourceMan;

        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValuifyAttributeAnalyzer_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Valuify.ValuifyAttributeAnalyzer.Resources", typeof(ValuifyAttributeAnalyzer_Resources).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Valuify attribute is only supported on class declarations..
        /// </summary>
        public static string CompatibleTargetTypeRuleDescription {
            get {
                return ResourceManager.GetString("CompatibleTargetTypeRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Valuify attribute is only supported on class declarations..
        /// </summary>
        public static string CompatibleTargetTypeRuleMessageFormat {
            get {
                return ResourceManager.GetString("CompatibleTargetTypeRuleMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not compatible with Valuify.
        /// </summary>
        public static string CompatibleTargetTypeRuleTitle {
            get {
                return ResourceManager.GetString("CompatibleTargetTypeRuleTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` does not define any properties to support equality checks..
        /// </summary>
        public static string DefinesPropertiesMessageFormat {
            get {
                return ResourceManager.GetString("DefinesPropertiesMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not define any properties to support equality checks..
        /// </summary>
        public static string DefinesPropertiesRuleDescription {
            get {
                return ResourceManager.GetString("DefinesPropertiesRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not define Properties.
        /// </summary>
        public static string DefinesPropertiesTitle {
            get {
                return ResourceManager.GetString("DefinesPropertiesTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuify cannot guarantee equality on type `{0} `because the inherited implementation for `{1}` is sealed..
        /// </summary>
        public static string EqualityGuarenteeMessageFormat {
            get {
                return ResourceManager.GetString("EqualityGuarenteeMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuify cannot guarantee equality because the inherited implementation has a required method..
        /// </summary>
        public static string EqualityGuarenteeRuleDescription {
            get {
                return ResourceManager.GetString("EqualityGuarenteeRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuify cannot guarantee Equality.
        /// </summary>
        public static string EqualityGuarenteeTitle {
            get {
                return ResourceManager.GetString("EqualityGuarenteeTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be marked as Partial to facilitate code generation..
        /// </summary>
        public static string PartialTypeRuleDescription {
            get {
                return ResourceManager.GetString("PartialTypeRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` must be marked as Partial to facilitate code generation..
        /// </summary>
        public static string PartialTypeRuleMessageFormat {
            get {
                return ResourceManager.GetString("PartialTypeRuleMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not Partial.
        /// </summary>
        public static string PartialTypeRuleTitle {
            get {
                return ResourceManager.GetString("PartialTypeRuleTitle", _resourceCulture);
            }
        }
    }
}
