//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valuify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EquatableStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquatableStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Valuify.Strategies.EquatableStrategy.Resources", typeof(EquatableStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partial class {0}
        ///    : IEquatable&lt;{0}&gt;
        ///{{
        ///}}.
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global::System.Collections.Generic.EqualityComparer&lt;{0}&gt;.
        /// </summary>
        internal static string EqualityComparer {
            get {
                return ResourceManager.GetString("EqualityComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partial class {0}
        ///{{
        ///    public bool Equals({0} other)
        ///    {{
        ///        if (ReferenceEquals(this, other))
        ///        {{
        ///            return true;
        ///        }}
        ///
        ///        if (ReferenceEquals(other, null))
        ///        {{
        ///            return false;
        ///        }}
        ///
        ///        return {1};
        ///    }}
        ///}}.
        /// </summary>
        internal static string Implementation {
            get {
                return ResourceManager.GetString("Implementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Default.Equals({1}, other.{1}).
        /// </summary>
        internal static string PropertyCondition {
            get {
                return ResourceManager.GetString("PropertyCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global::Valuify.Internal.SequenceEqualityComparer.
        /// </summary>
        internal static string SequenceComparer {
            get {
                return ResourceManager.GetString("SequenceComparer", resourceCulture);
            }
        }
    }
}
